/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBtn: typeof import('./src/components/AddBtn.vue')['default']
    AvailableBar: typeof import('./src/components/AvailableBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRate: typeof import('element-plus/es')['ElRate']
    IconComponent: typeof import('./src/components/IconComponent.vue')['default']
    MyIcons: typeof import('./src/components/MyIcons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Unit: typeof import('./src/components/Unit.vue')['default']
    UnitSummary: typeof import('./src/components/UnitSummary.vue')['default']
  }
}
