/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvailableBar: typeof import('./src/components/my-day-UI/AvailableBar.vue')['default']
    CreditResult: typeof import('./src/components/my-day-UI/CreditResult.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IconSelect: typeof import('./src/components/my-day-UI/IconSelect.vue')['default']
    ObjActivities: typeof import('./src/components/my-day-UI/ObjActivities.vue')['default']
    PersonalStatus: typeof import('./src/components/my-day-UI/PersonalStatus.vue')['default']
    PresetMenu: typeof import('./src/components/my-day-UI/PresetMenu.vue')['default']
    PresetsMenu: typeof import('./src/components/my-day-UI/PresetsMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpActivities: typeof import('./src/components/my-day-UI/SpActivities.vue')['default']
    SpUnit: typeof import('./src/components/SpUnit.vue')['default']
    Unit: typeof import('./src/components/Unit.vue')['default']
    UnitSummary: typeof import('./src/components/my-day-UI/UnitSummary.vue')['default']
    WkActivities: typeof import('./src/components/my-day-UI/WkActivities.vue')['default']
  }
}
