/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvailableBar: typeof import('./src/components/AvailableBar.vue')['default']
    CreditResult: typeof import('./src/components/CreditResult.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ObjActivities: typeof import('./src/components/ObjActivities.vue')['default']
    PersonalStatus: typeof import('./src/components/PersonalStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpActivities: typeof import('./src/components/SpActivities.vue')['default']
    SpUnit: typeof import('./src/components/SpUnit.vue')['default']
    SupportActivities: typeof import('./src/components/SupportActivities.vue')['default']
    Unit: typeof import('./src/components/Unit.vue')['default']
    UnitSummary: typeof import('./src/components/UnitSummary.vue')['default']
    WkActivities: typeof import('./src/components/WkActivities.vue')['default']
  }
}
